### ISSUE TITLE
Character limit on quotes

### ISSUE THREAD

**Issue by Ashna-git-hub** [Jacopo1891/MMM-RandomQuotes#5]
Could you have a character limit on quotes and some quotes take up the whole page and are paragraphs long

**Comment by Jacopo1891** [comment]
Good idea! I'm gonna add this! ;)

**Comment by Ashna-git-hub** [comment]
Thank you that's amazing

**Comment by Jacopo1891** [comment]
Try latest version 😀

**Comment by Ashna-git-hub** [comment]
Ahhhh wow you are outstanding! Thank you
